### ISSUE TITLE
Allow empty array for likes when posting to /fits

### ISSUE THREAD

**Issue by ekayy** [ekayy/fitted#16]
When posting to /fits

Likes array cannot be empty preventing fit creation without assigning a like.

Error message: 
This list may not be empty.

**Comment by wesleylulee** [comment]
I seem to be able to post a fit with an empty like array. I've used the following payload:

`{
    "profile": 55,
    "description": "test fit wiith with no likes",
    "style": 1,
    "photo": "foo.bar/outfit",
    "garment": [8,9,10]
}`

Can you show me the post you're trying to do?
