### ISSUE TITLE
KeyError for 'brandName' when POST to /garments

### ISSUE THREAD

**Issue by ekayy** [ekayy/fitted#29]
When trying to add custom garment and create a new garment through form:

"KeyError at /garments/
'brandName'

**Comment by wesleylulee** [comment]
I don't see this error when I attempt to create a garment. Can you show me the request you're making?

**Comment by ekayy** [comment]
<img width="1052" alt="Screen Shot 2019-10-03 at 8 08 48 PM" src="https://user-images.githubusercontent.com/1148941/66178305-a4810300-e619-11e9-8182-9fb6b6108547.png">

**Comment by wesleylulee** [comment]
@ekayy ah you should be using `brand_id` when you specify a brand and `brandName` when you specify the brand name string

**Comment by wesleylulee** [comment]
Gonna close, feel free to reopen if this is still an issue.
