### ISSUE TITLE
Show comment ids and replies when fetching garments

### ISSUE THREAD

**Issue by wesleylulee** [ekayy/fitted#38]

**Comment by wesleylulee** [comment]
done

**Comment by ekayy** [comment]
Hmm. Not sure if this was deployed. I don't see comment ids on the garments response. (If we were looking up replies through the comment id). Or if you wanted to just include replies in the garments response also?

**Comment by wesleylulee** [comment]
yeah I actually don't remember working on this so I must have close this by accident sorry! WIll work on this today

**Comment by wesleylulee** [comment]
Is something like this ok for accessing comments for a garment:

`
{
            "id": 1,
            "color": "Grey Chambray",
            "sku": "",
            "brand": 1,
            "brand_name": "3sixteen",
            "model": "Band Collar Shirt",
            "photo": "https://x",
            "purchase_page": "https://www.3sixteen.com/collections/shirts/products/long-sleeve-band-collar-grey-selvedge-chambray",
            "comments": [
                {
                    "id": 5,
                    "content": "garment comment",
                    "upvotes": 0,
                    "downvotes": 0,
                    "username": "Pat",
                    "replies": [
                        3,
                        4
                    ]
                }
            ]
        }
`

**Comment by ekayy** [comment]
Hey wes! not sure the best practice. but we can either display the full replies in there. or is there a way to look up all the replies by comment id. (like /comments/5/replies) or /replies/?ids=3,4 for example. so i dont have to request each reply individually?

**Comment by wesleylulee** [comment]
We might run into issues showing the full replies when the amount of replies gets too large but I will do that for now and we can figure out what to do when it gets too large

**Comment by wesleylulee** [comment]
just pushed this to prod
