### ISSUE TITLE
Can't post comment when setting content_type to garment

### ISSUE THREAD

**Issue by ekayy** [ekayy/fitted#49]
![image](https://user-images.githubusercontent.com/1148941/66877803-decc9780-ef6b-11e9-8692-4cabc652c16f.png)

**Comment by ekayy** [comment]
{
	"content_type": "garment",
	"object_id": 1,
	"profile": 20,
	"content": "foo"
}

**Comment by ekayy** [comment]
actually get this error as well on GET of http://ec2-54-67-49-101.us-west-1.compute.amazonaws.com/comments/

**Comment by wesleylulee** [comment]
sorry, this is due to a typo. This is why I should write unit tests lol. Just fixed this and will deploy tonight
